### ISSUE TITLE
Separate audio channel rendering

### ISSUE THREAD

**Issue by stijnfrishert** [Amjad50/mizu#3]
Hey!

I'm building a set of [command-line tools](https://crates.io/crates/lsdj-tools) for working with [Little Sound Dj](https://www.littlesounddj.com/lsd/index.php) files (a music tracker for the gameboy). Little Sound Dj musicians often render out the channels separately and then post-process them in their software of choice.

I know very little of gameboy emulation, but I thought it'd be cool if I could leverage `mizu-core` to do the audio rendering. Would it be possible to get out the four separate channel streams somehow, instead of just [`Gameboy::audio_buffer()`](https://docs.rs/mizu-core/0.2.0/mizu_core/struct.GameBoy.html#method.audio_buffer)?

If not, maybe it's possible to add solo/mute certain channels (I'd just run the emulator four times)?

**Comment by Amjad50** [comment]
Thanks for the suggestion, I changed the output of the `APU` to allow accessing each individual channel alone (as well as `all`).

**Comment by stijnfrishert** [comment]
Thanks, I think that would work! :)

**Comment by stijnfrishert** [comment]
Hmmm, maybe make the `AudioBuffers` struct public? I'm using it to collect all frame audio too.

**Comment by Amjad50** [comment]
Done. I'll add the other suggestions, fix issues, and release a new version later.

**Comment by stijnfrishert** [comment]
Thank you very much, all your work is much appreciated :)

I'd be happy to send in PRs too if that's easier/ok?

**Comment by Amjad50** [comment]
Of course PRs are welcome
