### ISSUE TITLE
Pass in a different path for SRAM

### ISSUE THREAD

**Issue by stijnfrishert** [Amjad50/mizu#5]
Right now [`GameBoy::new()`](https://docs.rs/mizu-core/0.2.0/mizu_core/struct.GameBoy.html#method.new) takes a ROM path and assumes the sav is next to it with `.sav` suffixed.

Can we change `new()` to take something like `sav: Option<P>`? Not all LSDJ sav files are stored next to a `.gb` with the same name.

**Comment by Amjad50** [comment]
Good suggestion, I'll add it
