### ISSUE TITLE
GameBoy shutdown always writes sav

### ISSUE THREAD

**Issue by stijnfrishert** [Amjad50/mizu#6]
This is more of a nitpick, but usually after rendering out audio using the LSDJ ROM I wouldn't want the sav to be rewritten. It updates the timestamp and internally the clock time is also saved in the LSDJ SRAM.

Is it an idea to add some way to not save on shutdown?

If that's too much of a hassle I can always copy the sram to a temporary file for my usage.

**Comment by Amjad50** [comment]
I suppose we can add an option to `GameboyConfig`, if I understood you correctly, you want to save the SRAM on the first run and then don't later?

**Comment by stijnfrishert** [comment]
No, I just want to load it and on `::new()`, but don't save it on shutdown.

**Comment by stijnfrishert** [comment]
Thanks, @Amjad50! 🙏
